# Game translation-unit manifest, generated from the *_src lists in makefile.gaz
# by port/cmake/gen_game_sources.sh - regenerate with that script, do not edit
# by hand.  289 TUs: all but system/main.cpp in the static lib (main is split
# out so test exes can supply their own main()).
# Dead .cpp files under source/ are deliberately absent - do NOT glob.

set(SBSP_GAME_MAIN_SOURCE ${SBSP_ROOT}/source/system/main.cpp)

set(SBSP_GAME_SOURCES
    ${SBSP_ROOT}/source/backend/credits.cpp
    ${SBSP_ROOT}/source/backend/gameover.cpp
    ${SBSP_ROOT}/source/backend/party.cpp
    ${SBSP_ROOT}/source/enemy/nanemone.cpp
    ${SBSP_ROOT}/source/enemy/nbblob.cpp
    ${SBSP_ROOT}/source/enemy/nbooger.cpp
    ${SBSP_ROOT}/source/enemy/nboss.cpp
    ${SBSP_ROOT}/source/enemy/nbuttfly.cpp
    ${SBSP_ROOT}/source/enemy/nclam.cpp
    ${SBSP_ROOT}/source/enemy/ndogfish.cpp
    ${SBSP_ROOT}/source/enemy/ndustdev.cpp
    ${SBSP_ROOT}/source/enemy/neyeball.cpp
    ${SBSP_ROOT}/source/enemy/nfdutch.cpp
    ${SBSP_ROOT}/source/enemy/nffolk.cpp
    ${SBSP_ROOT}/source/enemy/nfskull.cpp
    ${SBSP_ROOT}/source/enemy/ngen.cpp
    ${SBSP_ROOT}/source/enemy/ngeneric.cpp
    ${SBSP_ROOT}/source/enemy/nghost.cpp
    ${SBSP_ROOT}/source/enemy/nhcrab.cpp
    ${SBSP_ROOT}/source/enemy/nmjfish.cpp
    ${SBSP_ROOT}/source/enemy/nocto.cpp
    ${SBSP_ROOT}/source/enemy/npbug.cpp
    ${SBSP_ROOT}/source/enemy/npc.cpp
    ${SBSP_ROOT}/source/enemy/npcdata.cpp
    ${SBSP_ROOT}/source/enemy/npcpath.cpp
    ${SBSP_ROOT}/source/enemy/nprojjf.cpp
    ${SBSP_ROOT}/source/enemy/npuffa.cpp
    ${SBSP_ROOT}/source/enemy/nscrab.cpp
    ${SBSP_ROOT}/source/enemy/nsdart.cpp
    ${SBSP_ROOT}/source/enemy/nshell.cpp
    ${SBSP_ROOT}/source/enemy/nshrkman.cpp
    ${SBSP_ROOT}/source/enemy/nsj2back.cpp
    ${SBSP_ROOT}/source/enemy/nsjback.cpp
    ${SBSP_ROOT}/source/enemy/nsjfish.cpp
    ${SBSP_ROOT}/source/enemy/nsklfish.cpp
    ${SBSP_ROOT}/source/enemy/nsshark.cpp
    ${SBSP_ROOT}/source/enemy/nssnake.cpp
    ${SBSP_ROOT}/source/enemy/nsstomp.cpp
    ${SBSP_ROOT}/source/enemy/nworm.cpp
    ${SBSP_ROOT}/source/fileio/cdfile.cpp
    ${SBSP_ROOT}/source/fileio/fileio.cpp
    ${SBSP_ROOT}/source/fma/fma.cpp
    ${SBSP_ROOT}/source/fmv/fmv.cpp
    ${SBSP_ROOT}/source/friend/fdata.cpp
    ${SBSP_ROOT}/source/friend/fgary.cpp
    ${SBSP_ROOT}/source/friend/fkrusty.cpp
    ${SBSP_ROOT}/source/friend/fpatrick.cpp
    ${SBSP_ROOT}/source/friend/friend.cpp
    ${SBSP_ROOT}/source/friend/fsandy.cpp
    ${SBSP_ROOT}/source/friend/fsquid.cpp
    ${SBSP_ROOT}/source/frontend/demomode.cpp
    ${SBSP_ROOT}/source/frontend/fmvad.cpp
    ${SBSP_ROOT}/source/frontend/fmvintro.cpp
    ${SBSP_ROOT}/source/frontend/fmvthq.cpp
    ${SBSP_ROOT}/source/frontend/frontend.cpp
    ${SBSP_ROOT}/source/frontend/maintitl.cpp
    ${SBSP_ROOT}/source/frontend/nicklogo.cpp
    ${SBSP_ROOT}/source/frontend/options.cpp
    ${SBSP_ROOT}/source/frontend/scrollbg.cpp
    ${SBSP_ROOT}/source/frontend/start.cpp
    ${SBSP_ROOT}/source/fx/fx.cpp
    ${SBSP_ROOT}/source/fx/fxbaseanim.cpp
    ${SBSP_ROOT}/source/fx/fxbaseemitter.cpp
    ${SBSP_ROOT}/source/fx/fxbasetrail.cpp
    ${SBSP_ROOT}/source/fx/fxbubble.cpp
    ${SBSP_ROOT}/source/fx/fxfallingtile.cpp
    ${SBSP_ROOT}/source/fx/fxfire.cpp
    ${SBSP_ROOT}/source/fx/fxgeyser.cpp
    ${SBSP_ROOT}/source/fx/fxjfish.cpp
    ${SBSP_ROOT}/source/fx/fxlaser.cpp
    ${SBSP_ROOT}/source/fx/fxnrgbar.cpp
    ${SBSP_ROOT}/source/fx/fxsmoke.cpp
    ${SBSP_ROOT}/source/fx/fxsteam.cpp
    ${SBSP_ROOT}/source/fx/fxthwack.cpp
    ${SBSP_ROOT}/source/fx/fxtvexplode.cpp
    ${SBSP_ROOT}/source/fx/fxzzzz.cpp
    ${SBSP_ROOT}/source/game/bosstext.cpp
    ${SBSP_ROOT}/source/game/convo.cpp
    ${SBSP_ROOT}/source/game/game.cpp
    ${SBSP_ROOT}/source/game/gamebubs.cpp
    ${SBSP_ROOT}/source/game/gameslot.cpp
    ${SBSP_ROOT}/source/game/healthman.cpp
    ${SBSP_ROOT}/source/game/pause.cpp
    ${SBSP_ROOT}/source/gfx/actor.cpp
    ${SBSP_ROOT}/source/gfx/animtex.cpp
    ${SBSP_ROOT}/source/gfx/bubicles.cpp
    ${SBSP_ROOT}/source/gfx/fader.cpp
    ${SBSP_ROOT}/source/gfx/fdata.cpp
    ${SBSP_ROOT}/source/gfx/font.cpp
    ${SBSP_ROOT}/source/gfx/prim.cpp
    ${SBSP_ROOT}/source/gfx/sprbank.cpp
    ${SBSP_ROOT}/source/gfx/tpage.cpp
    ${SBSP_ROOT}/source/gui/gbutton.cpp
    ${SBSP_ROOT}/source/gui/gfactory.cpp
    ${SBSP_ROOT}/source/gui/gframe.cpp
    ${SBSP_ROOT}/source/gui/greadout.cpp
    ${SBSP_ROOT}/source/gui/gsprite.cpp
    ${SBSP_ROOT}/source/gui/gtextbox.cpp
    ${SBSP_ROOT}/source/gui/gui.cpp
    ${SBSP_ROOT}/source/gui/pointer.cpp
    ${SBSP_ROOT}/source/hazard/hazard.cpp
    ${SBSP_ROOT}/source/hazard/hbarrel.cpp
    ${SBSP_ROOT}/source/hazard/hbbarrel.cpp
    ${SBSP_ROOT}/source/hazard/hboat.cpp
    ${SBSP_ROOT}/source/hazard/hbrock.cpp
    ${SBSP_ROOT}/source/hazard/hbwheel.cpp
    ${SBSP_ROOT}/source/hazard/hcheck.cpp
    ${SBSP_ROOT}/source/hazard/hcsaw.cpp
    ${SBSP_ROOT}/source/hazard/hcswitch.cpp
    ${SBSP_ROOT}/source/hazard/hdbarrel.cpp
    ${SBSP_ROOT}/source/hazard/hfalling.cpp
    ${SBSP_ROOT}/source/hazard/hfan.cpp
    ${SBSP_ROOT}/source/hazard/hfirebal.cpp
    ${SBSP_ROOT}/source/hazard/hflytrap.cpp
    ${SBSP_ROOT}/source/hazard/hinert.cpp
    ${SBSP_ROOT}/source/hazard/hlog.cpp
    ${SBSP_ROOT}/source/hazard/hmasher.cpp
    ${SBSP_ROOT}/source/hazard/hmower.cpp
    ${SBSP_ROOT}/source/hazard/hpendulm.cpp
    ${SBSP_ROOT}/source/hazard/hpswitch.cpp
    ${SBSP_ROOT}/source/hazard/hrckshrd.cpp
    ${SBSP_ROOT}/source/hazard/hrrock.cpp
    ${SBSP_ROOT}/source/hazard/hrweight.cpp
    ${SBSP_ROOT}/source/hazard/hsaw.cpp
    ${SBSP_ROOT}/source/hazard/hspikes.cpp
    ${SBSP_ROOT}/source/hazard/hsrdfish.cpp
    ${SBSP_ROOT}/source/jellfish/jellfish.cpp
    ${SBSP_ROOT}/source/level/layerback.cpp
    ${SBSP_ROOT}/source/level/layercollision.cpp
    ${SBSP_ROOT}/source/level/layertile.cpp
    ${SBSP_ROOT}/source/level/layertile3d.cpp
    ${SBSP_ROOT}/source/level/level.cpp
    ${SBSP_ROOT}/source/locale/textdbase.cpp
    ${SBSP_ROOT}/source/map/map.cpp
    ${SBSP_ROOT}/source/mem/memory.cpp
    ${SBSP_ROOT}/source/memcard/md5.cpp
    ${SBSP_ROOT}/source/memcard/memcard.cpp
    ${SBSP_ROOT}/source/memcard/saveload.cpp
    ${SBSP_ROOT}/source/pad/padicon.cpp
    ${SBSP_ROOT}/source/pad/pads.cpp
    ${SBSP_ROOT}/source/pad/vibe.cpp
    ${SBSP_ROOT}/source/paul/animtest.cpp
    ${SBSP_ROOT}/source/paul/paul.cpp
    ${SBSP_ROOT}/source/paul/scenesel.cpp
    ${SBSP_ROOT}/source/paul/sndtest.cpp
    ${SBSP_ROOT}/source/pickups/pballoon.cpp
    ${SBSP_ROOT}/source/pickups/pblower.cpp
    ${SBSP_ROOT}/source/pickups/pbubmix.cpp
    ${SBSP_ROOT}/source/pickups/pglove.cpp
    ${SBSP_ROOT}/source/pickups/phelmet.cpp
    ${SBSP_ROOT}/source/pickups/pickup.cpp
    ${SBSP_ROOT}/source/pickups/pjlammo.cpp
    ${SBSP_ROOT}/source/pickups/pkelp.cpp
    ${SBSP_ROOT}/source/pickups/plife.cpp
    ${SBSP_ROOT}/source/pickups/pnet.cpp
    ${SBSP_ROOT}/source/pickups/pquest.cpp
    ${SBSP_ROOT}/source/pickups/pshoes.cpp
    ${SBSP_ROOT}/source/pickups/pspatula.cpp
    ${SBSP_ROOT}/source/platform/pbaloon.cpp
    ${SBSP_ROOT}/source/platform/pbgeyser.cpp
    ${SBSP_ROOT}/source/platform/pbob.cpp
    ${SBSP_ROOT}/source/platform/pbounce.cpp
    ${SBSP_ROOT}/source/platform/pbranch.cpp
    ${SBSP_ROOT}/source/platform/pbubble.cpp
    ${SBSP_ROOT}/source/platform/pbubtube.cpp
    ${SBSP_ROOT}/source/platform/pbwheel.cpp
    ${SBSP_ROOT}/source/platform/pcart.cpp
    ${SBSP_ROOT}/source/platform/pcbubble.cpp
    ${SBSP_ROOT}/source/platform/pcirculr.cpp
    ${SBSP_ROOT}/source/platform/pclam.cpp
    ${SBSP_ROOT}/source/platform/pconveyr.cpp
    ${SBSP_ROOT}/source/platform/pdrop.cpp
    ${SBSP_ROOT}/source/platform/pdual.cpp
    ${SBSP_ROOT}/source/platform/pfalling.cpp
    ${SBSP_ROOT}/source/platform/pfallnor.cpp
    ${SBSP_ROOT}/source/platform/pfblock.cpp
    ${SBSP_ROOT}/source/platform/pfgen.cpp
    ${SBSP_ROOT}/source/platform/pfishhk.cpp
    ${SBSP_ROOT}/source/platform/pfishhk3.cpp
    ${SBSP_ROOT}/source/platform/pgbubble.cpp
    ${SBSP_ROOT}/source/platform/pgeyser.cpp
    ${SBSP_ROOT}/source/platform/pghost.cpp
    ${SBSP_ROOT}/source/platform/pjellfsh.cpp
    ${SBSP_ROOT}/source/platform/plantern.cpp
    ${SBSP_ROOT}/source/platform/platdata.cpp
    ${SBSP_ROOT}/source/platform/platform.cpp
    ${SBSP_ROOT}/source/platform/pleaf.cpp
    ${SBSP_ROOT}/source/platform/plift.cpp
    ${SBSP_ROOT}/source/platform/plinear.cpp
    ${SBSP_ROOT}/source/platform/plurve.cpp
    ${SBSP_ROOT}/source/platform/ppendulm.cpp
    ${SBSP_ROOT}/source/platform/pplayer.cpp
    ${SBSP_ROOT}/source/platform/praft.cpp
    ${SBSP_ROOT}/source/platform/prbridge.cpp
    ${SBSP_ROOT}/source/platform/pretract.cpp
    ${SBSP_ROOT}/source/platform/psbarrel.cpp
    ${SBSP_ROOT}/source/platform/pseesaw.cpp
    ${SBSP_ROOT}/source/platform/psswitch.cpp
    ${SBSP_ROOT}/source/platform/ptrpdoor.cpp
    ${SBSP_ROOT}/source/player/demoplay.cpp
    ${SBSP_ROOT}/source/player/panimsfx.cpp
    ${SBSP_ROOT}/source/player/player.cpp
    ${SBSP_ROOT}/source/player/pmbloon.cpp
    ${SBSP_ROOT}/source/player/pmbubble.cpp
    ${SBSP_ROOT}/source/player/pmcart.cpp
    ${SBSP_ROOT}/source/player/pmchop.cpp
    ${SBSP_ROOT}/source/player/pmcoral.cpp
    ${SBSP_ROOT}/source/player/pmdead.cpp
    ${SBSP_ROOT}/source/player/pmfly.cpp
    ${SBSP_ROOT}/source/player/pmjelly.cpp
    ${SBSP_ROOT}/source/player/pmnet.cpp
    ${SBSP_ROOT}/source/player/pmodes.cpp
    ${SBSP_ROOT}/source/player/pmswal.cpp
    ${SBSP_ROOT}/source/player/psbutt.cpp
    ${SBSP_ROOT}/source/player/pscart.cpp
    ${SBSP_ROOT}/source/player/psdance.cpp
    ${SBSP_ROOT}/source/player/psduck.cpp
    ${SBSP_ROOT}/source/player/psfall.cpp
    ${SBSP_ROOT}/source/player/psfloat.cpp
    ${SBSP_ROOT}/source/player/pshitgnd.cpp
    ${SBSP_ROOT}/source/player/psidle.cpp
    ${SBSP_ROOT}/source/player/psjmpbck.cpp
    ${SBSP_ROOT}/source/player/psjump.cpp
    ${SBSP_ROOT}/source/player/pslook.cpp
    ${SBSP_ROOT}/source/player/psrun.cpp
    ${SBSP_ROOT}/source/player/psspring.cpp
    ${SBSP_ROOT}/source/player/psswal.cpp
    ${SBSP_ROOT}/source/projectl/prnpc.cpp
    ${SBSP_ROOT}/source/projectl/prnpcspr.cpp
    ${SBSP_ROOT}/source/projectl/projectl.cpp
    ${SBSP_ROOT}/source/save/save.cpp
    ${SBSP_ROOT}/source/script/function.cpp
    ${SBSP_ROOT}/source/script/script.cpp
    ${SBSP_ROOT}/source/shop/shop.cpp
    ${SBSP_ROOT}/source/sound/cdxa.cpp
    ${SBSP_ROOT}/source/sound/sound.cpp
    ${SBSP_ROOT}/source/sound/spu.cpp
    ${SBSP_ROOT}/source/sound/xmplay.cpp
    ${SBSP_ROOT}/source/system/clickcount.cpp
    ${SBSP_ROOT}/source/system/dbg.cpp
    ${SBSP_ROOT}/source/system/except.cpp
    ${SBSP_ROOT}/source/system/gstate.cpp
    ${SBSP_ROOT}/source/system/vid.cpp
    ${SBSP_ROOT}/source/system/vsprintf.cpp
    ${SBSP_ROOT}/source/thing/thing.cpp
    ${SBSP_ROOT}/source/triggers/tabemit.cpp
    ${SBSP_ROOT}/source/triggers/tadripemit.cpp
    ${SBSP_ROOT}/source/triggers/tbemit.cpp
    ${SBSP_ROOT}/source/triggers/tbgeyser.cpp
    ${SBSP_ROOT}/source/triggers/tboss.cpp
    ${SBSP_ROOT}/source/triggers/tbuttfly.cpp
    ${SBSP_ROOT}/source/triggers/tcamlock.cpp
    ${SBSP_ROOT}/source/triggers/tfemit.cpp
    ${SBSP_ROOT}/source/triggers/tgarygo.cpp
    ${SBSP_ROOT}/source/triggers/tgbowl.cpp
    ${SBSP_ROOT}/source/triggers/tggleft.cpp
    ${SBSP_ROOT}/source/triggers/tggright.cpp
    ${SBSP_ROOT}/source/triggers/tgstop.cpp
    ${SBSP_ROOT}/source/triggers/thazard.cpp
    ${SBSP_ROOT}/source/triggers/thazwalk.cpp
    ${SBSP_ROOT}/source/triggers/tifemit.cpp
    ${SBSP_ROOT}/source/triggers/tlbemit.cpp
    ${SBSP_ROOT}/source/triggers/tldripemit.cpp
    ${SBSP_ROOT}/source/triggers/tlevexit.cpp
    ${SBSP_ROOT}/source/triggers/tlook.cpp
    ${SBSP_ROOT}/source/triggers/tobemit.cpp
    ${SBSP_ROOT}/source/triggers/todripemit.cpp
    ${SBSP_ROOT}/source/triggers/toilgeyser.cpp
    ${SBSP_ROOT}/source/triggers/tplatfrm.cpp
    ${SBSP_ROOT}/source/triggers/trestart.cpp
    ${SBSP_ROOT}/source/triggers/trigger.cpp
    ${SBSP_ROOT}/source/triggers/tsdownemit.cpp
    ${SBSP_ROOT}/source/triggers/tsecret.cpp
    ${SBSP_ROOT}/source/triggers/tsemit.cpp
    ${SBSP_ROOT}/source/triggers/tsleftemit.cpp
    ${SBSP_ROOT}/source/triggers/tspeech.cpp
    ${SBSP_ROOT}/source/triggers/tsrightemit.cpp
    ${SBSP_ROOT}/source/triggers/tsswitch.cpp
    ${SBSP_ROOT}/source/triggers/tteleprt.cpp
    ${SBSP_ROOT}/source/triggers/twater.cpp
    ${SBSP_ROOT}/source/triggers/twdripemit.cpp
    ${SBSP_ROOT}/source/triggers/twinddown.cpp
    ${SBSP_ROOT}/source/triggers/twindleft.cpp
    ${SBSP_ROOT}/source/triggers/twindright.cpp
    ${SBSP_ROOT}/source/triggers/twindup.cpp
    ${SBSP_ROOT}/source/utils/lznp.cpp
    ${SBSP_ROOT}/source/utils/sincos.cpp
    ${SBSP_ROOT}/source/utils/utils.cpp
)
